language: python
python: 3.5

sudo: false

install:
  - travis_retry pip install -e .[test]

script:
  - python3 -m pytest
  - sphinx-build -nq -b html -b linkcheck -d docs/_build/doctrees docs docs/_build/html
