matrix:
  include:
    - language: python
      python: 3.6
      os: linux
    - os: windows
      language: sh # Python is not yet officially supported
  allow_failures:
    - os: windows
      language: sh
  fast_finish: true

sudo: false
cache: pip

before_install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install python3
      ln -s $(which py) /usr/bin/python3
    fi

install:
  - travis_retry python3 -m pip install -e .[test]

script:
  - python3 -m pytest
  - sphinx-build -q -b html -b linkcheck -d docs/_build/doctrees docs docs/_build/html
